name = "TextPieces"
uuid = "49c2a6ab-405b-4d52-ba23-488dbb8b2dec"
authors = ["chengchingwen <chengchingwen214@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
